# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('decription', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('ingredients', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cooktime', models.IntegerField()),
                ('difficulty', models.CharField(max_length=10)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetbook.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetbook.Comment')),
                ('event', models.ManyToManyField(to='sweetbook.Event')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetbook.Recipe')),
            ],
        ),
    ]
